### ISSUE TITLE
ZeroDivisionError with sector-coupling mvs input in main

### ISSUE THREAD

**Issue by MaGering** [greco-project/pvcompare#127]
The sector-coupling example is not running due to a ZeroDivisionError. While adding components to oemof energy system model the simulation stops with this error message:

`ERROR: Constructing component 'Transformer.relation_build' from data=None
    failed: ZeroDivisionError:
15:43:59-ERROR-Constructing component 'Transformer.relation_build' from data=None failed:
ZeroDivisionError: 

Process finished with exit code 1`

I have already checked the inputs of the transformers in energyConversion.csv Changing values there from zero to other values did not work.

**Comment by SabineHaas** [comment]
So, the difference between our errors is: I haven't deleted my old "COPs"-file which was still containing `nans` instead of zeros. 
Using the [zip file you have sent me](https://github.com/greco-project/pvcompare/files/5476549/mvs_inputs_template_sector_coupling.zip) I get a ZeroDivisionError, as well, see [error_msg.txt](https://github.com/greco-project/pvcompare/files/5476565/error_msg.txt).

 I don't get the ZeroDivisionError when using  [my old cop file containing nans](https://github.com/greco-project/pvcompare/files/5476844/cops.zip). Then the error was `ValueError: No value for uninitialized NumericValue object InvestmentFlow.invest[Heat pump,Heat_bus]`.

I can make the simulation run through by choosing room_temperature = 60 and start_temperature = 50.
Can you check your settings? In your timeseries folder the cops still contain zeros, with the above adjustment, the demand can be covered, as no zeros occur.

**Comment by MaGering** [comment]
Thank you for the explanation. It was really helpful! The simulation runs through with your chosen values and fails when I use COPs containing nan for me as well. :)
