### ISSUE TITLE
Build for master fails

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#262]
I manually triggered builds for `master` : https://github.com/greco-project/pvcompare/runs/2166871352?check_suite_focus=true
and `dev`: https://github.com/greco-project/pvcompare/actions/runs/676370346

While the build for `dev` passes, the build for `master` fails at `TestTES.test_implementations_tes` in `tests/test_main.py`.

I understand that this is a test that is not carried out for `dev` (only for `EXECUTE_TESTS_ON=="master"`.

@MaGering could you locally run this test in master and check the error please? I don't know why I did not see this error when testing before the release.

**Comment by MaGering** [comment]
> While the build for `dev` passes, the build for `master` fails at `TestTES.test_implementations_tes` in `tests/test_main.py`.
> 
> I understand that this is a test that is not carried out for `dev` (only for `EXECUTE_TESTS_ON=="master"`.

These are probably two different things. `test_implementations_tes` is a function in `tests/test_stratified_thermal_storage.py` and not in `tests/test_main.py`. Why you had this error is probably because one of the tests in `tests/test_stratified_thermal_storage.py` failed and the directory `Test_Scenario_TES` had not been deleted as it should have been. The next time you ran the tests after fixing maybe something different, `tests/test_stratified_thermal_storage.py` failed because `Test_Scenario_TES` exists. You need to delete it to fix this problem.

I found an error in `tests/test_main.py` in its input data (`fixcosts.csv`) But there are still other errors I will try to fix now.

**Comment by SabineHaas** [comment]
Fixed with #263
