### ISSUE TITLE
calculation of yearly time series reasonable?

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#36]
After our discussion on the project duration I asked myself whether it makes sense to calculate year-specific timeseries in pvcompare if the project duration is greater then one year anyways. It is kind of time consuming to always calculate the timeseries anew. Of course the option should be available, but maybe it would make sence to have "default" timeseries for a 'random' year for each location that can be used if the project duration >> 1 year. So my question is: would we then just calculate a timeseries of any year, or should we reather add a TMY year (this is not available in era5 and would need to be implemented)?

any ideas on that?

**Comment by SabineHaas** [comment]
I see two questions here

1. I never checked for TMYs for every country of Europe but it might be time consuming to gather them. So if we would want to pre-calculate time series I would go for ERA5. As we wouldn't provide time series for every weather data point in Europe (that would be a enormous data set) but rather for countries, I don't see a problem in choosing one year as the location of the time series also wouldn't be the exact choice for many occasions. 

2. I am not sure whether we would add something useful and new. Firstly, PV time series for Europe can be calculated from [renewables ninja](https://www.renewables.ninja/downloads)'s capacity factors. So this work is already done for state-of-the-art PV. Secondly, concerning the new technologies I think it's not the time, yet, to provide such data, as we didn't validate the functionalities, yet.

Instead, 3. we could provide downloaded ERA5 data (because this is the part taking most of the time, right?).. Whole Europe is probably too big for a csv in the repo - but we could think of another means of sharing the data set (oedb?) or reducing it.
