### ISSUE TITLE
definition maximum power point

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#77]
Hi,
I noticed that there might be a confusion with the definition of maximum power point. The nominal value is defined by: 
`nominal value = area / module_size * p_mp`

right now p_mp is taken from module parameters at reference conditions. So it is the mpp at 25°C (that's how it is defined in pvlib).

But the nominal value should take the maximum possible pp at any weather conditions into account, right?

**Comment by SabineHaas** [comment]
I'm not sure whether we can retrieve this value (maximum pp at any weather conditions). 

For calculating the installed capacity it's fine to use the p_mp at reference conditions - as this is the standard, everyone understands what we are talking about. 

However, a problem might occur in case a pv time series contains a value > p_mp, in case we normalize the time series with the p_mp instead of the maximum value of the time series.

**Comment by Piranias** [comment]
see issue #50

**Comment by Piranias** [comment]
if i remember correct right now mvs does the normalization, right? So we enter the absolute timeseries and mvs calculates how many of these modules need to be built. MVS then takes the maximum value of the timeseries for normalization.
@SabineHaas Do you agree with this?

**Comment by SabineHaas** [comment]
> if i remember correct right now mvs does the normalization, right? So we enter the absolute timeseries and mvs calculates how many of these modules need to be built. MVS then takes the maximum value of the timeseries for normalization.
> @SabineHaas Do you agree with this?

I wrote it on the list for tomorrows meeting because I remember that MVS requires normalized time series for RE but I am not sure.
